# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160601_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_stock_status',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StockStatus',
        ),
    ]
