# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160602_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_stock_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockStatus', verbose_name='Stock Status'),
        ),
    ]
