# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160602_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=300, verbose_name='Item')),
                ('item_stock_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockStatus', verbose_name='Stock Status')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='item_active',
            field=models.BooleanField(default=datetime.datetime(2016, 6, 2, 7, 25, 28, 91256, tzinfo=utc), verbose_name=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='item_location',
            field=models.CharField(default=datetime.datetime(2016, 6, 2, 7, 25, 33, 10538, tzinfo=utc), max_length=300, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
