# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20160605_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_location',
            field=models.CharField(max_length=300, null=True, verbose_name='Location'),
        ),
    ]
