# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_name', models.CharField(blank=True, max_length=300, verbose_name='Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300, verbose_name='Product')),
                ('item_location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Location')),
                ('item_active', models.BooleanField(default=True, verbose_name='Active')),
                ('slug', models.SlugField()),
                ('item_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer', verbose_name='Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=300, verbose_name='Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='stock_status',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RenameField(
            model_name='stockstatus',
            old_name='name',
            new_name='stock_stage',
        ),
        migrations.RemoveField(
            model_name='stockstatus',
            name='description',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddField(
            model_name='recipes',
            name='item_stock_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockStatus', verbose_name='Stock Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_stock_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockStatus', verbose_name='Stock Status'),
        ),
    ]
