# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='stock_status',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='StockStatus',
        ),
    ]
