# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_auto_20160601_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_name', models.CharField(blank=True, max_length=300)),
                ('mfg_url', models.URLField(blank=True, max_length=300)),
                ('username', models.CharField(blank=True, max_length=300)),
                ('password', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Status',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='item_stock_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockStatus'),
        ),
    ]
