# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160606_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 6, 6, 4, 53, 52, 135731, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
