# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20160602_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
