# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20160602_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.CharField(max_length=300, verbose_name='Product'),
        ),
    ]
