# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160602_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_slug',
            field=models.SlugField(default=datetime.datetime(2016, 6, 5, 22, 43, 11, 421870, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
