# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_slug',
            new_name='slug',
        ),
    ]
